const Menu = [
  {
    id: 1,
    name: "Virat Kohali",
    title: "batsman",
    Image: "image/viart.jpg",
    description: "age-28,INDIA",
    category: "batsman",
  },
  {
    id: 2,
    name: "HARDIK PANDYA",
    title: "ALL-ROUNDER",
    Image: "image/hardik.jpg",
    description: "age-28,INDIA",
    category: "ALL-ROUNDER",
  },
  {
    id: 3,
    name: "ROHIT SHARMA",
    title: "batsman",
    Image: "image/rohit.jpg",
    description: "age-36,INDIA",
    category: "batsman",
  },
  {
    id: 4,
    name: "Suryakumar Yadev",
    title: "batsman",
    Image: "image/Suryakumar-yadav.png",
    description: "age-30,INDIA",
    category: "batsman",
  },
  {
    id: 5,
    name: "KL rahul",
    title: "bowler",
    Image: "image/kl-rahul.jpg",
    description: "age-28,INDIA",
    category: "bowler",
  },
  {
    id: 6,
    name: "Rishabh pant",
    title: "batsman",
    Image: "image/rihsev-pant.webp",
    description: "age-26,INDIA",
    category: "batsman",
  },
  {
    id: 7,
    name: "MS DHONI",
    title: "batsman",
    Image: "image/dhoni.webp",
    description: "age-41,INDIA",
    category: "batsman",
  },
  {
    id: 8,
    name: "Jasprit Bumrah",
    title: "bowler",
    Image: "image/bumrah.webp",
    description: "age-28,INDIA",
    category: "bowler",
  },
  {
    id: 9,
    name: "Bhuvneshwer Kumar",
    title: "batsman",
    Image: "image/b kuamr.webp",
    description: "age-31,INDIA",
    category: "batsman",
  },
  {
    id: 10,
    name: "Mohammed Shami",
    title: "bowler",
    Image: "image/mohammedshami.webp",
    description: "age-36,INDIA",
    category: "bowler",
  },
  {
    id: 11,
    name: "Yuzvendra Chahal",
    title: "Bowler",
    Image: "image/chahal.webp",
    description: "age-31,INDIA",
    category: "bowler",
  },
  {
    id: 12,
    name: "Kuldeep Yadev",
    title: "Bowler",
    Image: "image/kuldeep.webp",
    description: "age-32,INDIA",
    category: "bowler",
  },
  {
    id: 13,
    name: "Shahbaz Ahmedv",
    title: "All-rounder",
    Image: "image/ahamad.jpg",
    description: "age-36,INDIA",
    category: "ALL-ROUNDER",
  },
  {
    id: 14,
    name: "Ravindra Jedeja",
    title: "All-rounder",
    Image: "image/jadeja.webp",
    description: "age-35,INDIA",
    category: "ALL-ROUNDER",
  },
];
export default Menu;
